name: ttrpg_tools
description: A set of utilities for game mechanics.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  quiver: ^3.2.1
  xml: ^6.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
